/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 18 07:34:10 GMT 2023
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.CharacterReader;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CharacterReader_ESTest extends CharacterReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.rewindToMark();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("qkWr!lB]Aza`KGf*");
      characterReader0.matchConsumeIgnoreCase("h3\r\n?");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Iz}(v57!u?^8!b");
      characterReader0.mark();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.advance();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?tv");
      characterReader0.matchConsume("h3\r\n?");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader(">\"qM\u00049^_`S-v");
      characterReader0.unconsume();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.toString();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?tv");
      characterReader0.consumeToEnd();
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("j#kZHFf/8");
      characterReader0.pos();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("j#kZHFf/8");
      characterReader0.current();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("org.jsoup.parser.CharacterReader");
      characterReader0.consumeToEnd();
      characterReader0.current();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.consume();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("e");
      characterReader0.consumeTo('q');
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Array must not contain any null objects");
      characterReader0.consumeTo('l');
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H34\".");
      characterReader0.consumeTo("");
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("3]k? JLYirwziMvP]");
      char[] charArray0 = new char[6];
      charArray0[3] = 'i';
      characterReader0.consumeToAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H34\".");
      characterReader0.matchConsume("H34\".");
      char[] charArray0 = new char[2];
      characterReader0.consumeToAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Us&oi-I[CI#)d");
      characterReader0.matchConsumeIgnoreCase("Us&oi-I[CI#)d");
      characterReader0.consumeLetterSequence();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Iz}(v57!u?^8!b");
      characterReader0.consumeLetterSequence();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("/");
      characterReader0.consumeAsString();
      characterReader0.consumeLetterThenDigitSequence();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("Iz}(v57!u?^8!b");
      characterReader0.consumeLetterThenDigitSequence();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H34\".");
      characterReader0.consumeLetterThenDigitSequence();
      characterReader0.matches('\"');
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("e");
      characterReader0.consumeHexSequence();
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H34\".");
      characterReader0.consume();
      characterReader0.consumeHexSequence();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("^BtYX/");
      characterReader0.consumeAsString();
      characterReader0.consumeHexSequence();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("#~M51n{)|yfWmM3]k? JLYirwziMvP]");
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("3]k? JLYirwziMvP]");
      characterReader0.consumeDigitSequence();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matches(' ');
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("!!");
      characterReader0.matches('\"');
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?tv");
      char[] charArray0 = new char[7];
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("j#kZHFf/8");
      char[] charArray0 = new char[2];
      characterReader0.consumeLetterSequence();
      characterReader0.consumeTo("j");
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?tv");
      char[] charArray0 = new char[7];
      charArray0[0] = 'w';
      characterReader0.matchesAny(charArray0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("GF(");
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("");
      characterReader0.matchesLetter();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("3]k? JLYirwziMvP]");
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("e");
      characterReader0.consumeHexSequence();
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("\n");
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("UJ {XXG^U\"M^s0CE.X");
      characterReader0.matchesDigit();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.containsIgnoreCase("");
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.containsIgnoreCase("us&oi-i[ci#");
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("wt,?*V");
      characterReader0.containsIgnoreCase("V");
  }
}
