/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 25 05:23:39 GMT 2023
 */

package com.google.gson.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.GenericArrayType;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.lang.reflect.WildcardType;
import java.util.Properties;
import java.util.function.BiFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class $Gson$Types_ESTest extends $Gson$Types_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<Properties> class1 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class1);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class1, class1, typeArray0);
      Type type0 = .Gson.Types.resolve(class1, class1, parameterizedType0);
      assertNotNull(type0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf(class0);
      Class<?> class1 = .Gson.Types.getRawType(genericArrayType0);
      Class class2 = (Class).Gson.Types.resolve(class0, class0, class1);
      assertEquals(1041, class2.getModifiers());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      Type type0 = .Gson.Types.resolve(wildcardType0, class0, wildcardType0);
      assertNotNull(type0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.supertypeOf(class0);
      Type[] typeArray0 = new Type[1];
      typeArray0[0] = (Type) wildcardType0;
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class0, wildcardType0, typeArray0);
      Properties properties0 = new Properties();
      BiFunction<Object, Object, Object> biFunction0 = (BiFunction<Object, Object, Object>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      Object object0 = properties0.computeIfPresent(parameterizedType0, biFunction0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class0);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class0, class0, typeArray0);
      Type type0 = .Gson.Types.canonicalize(parameterizedType0);
      assertNotNull(type0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      WildcardType wildcardType1 = .Gson.Types.subtypeOf(wildcardType0);
      assertTrue(wildcardType1.equals((Object)wildcardType0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      WildcardType wildcardType1 = .Gson.Types.supertypeOf(wildcardType0);
      assertNotSame(wildcardType0, wildcardType1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf(class0);
      Class<?> class1 = .Gson.Types.getRawType(genericArrayType0);
      Type type0 = .Gson.Types.getGenericSupertype(class1, class1, class1);
      GenericArrayType genericArrayType1 = .Gson.Types.arrayOf(type0);
      assertNotSame(genericArrayType1, genericArrayType0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf(wildcardType0);
      WildcardType wildcardType1 = .Gson.Types.supertypeOf(genericArrayType0);
      boolean boolean0 = .Gson.Types.equals((Type) wildcardType0, (Type) wildcardType1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      // Undeclared exception!
      try { 
        .Gson.Types.getRawType(genericArrayType0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null
         //
         verifyException("com.google.gson.internal.$Gson$Types", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class0);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class0, class0, typeArray0);
      Class<?> class1 = .Gson.Types.getRawType(parameterizedType0);
      assertEquals("class java.util.Properties", class1.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      Class<?> class1 = .Gson.Types.getRawType(wildcardType0);
      assertEquals("class java.lang.Integer", class1.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      boolean boolean0 = .Gson.Types.equal(wildcardType0, wildcardType0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      WildcardType wildcardType1 = .Gson.Types.subtypeOf(class0);
      boolean boolean0 = .Gson.Types.equal(wildcardType0, wildcardType1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Properties properties0 = new Properties();
      boolean boolean0 = .Gson.Types.equal((Object) null, properties0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf(class0);
      boolean boolean0 = .Gson.Types.equals((Type) class0, (Type) genericArrayType0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<Properties> class1 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class1);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class1, class1, typeArray0);
      boolean boolean0 = .Gson.Types.equals((Type) parameterizedType0, (Type) class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      GenericArrayType genericArrayType1 = .Gson.Types.arrayOf((Type) null);
      boolean boolean0 = .Gson.Types.equals((Type) genericArrayType1, (Type) genericArrayType0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      boolean boolean0 = .Gson.Types.equals((Type) genericArrayType0, (Type) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      boolean boolean0 = .Gson.Types.equals((Type) null, (Type) genericArrayType0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      boolean boolean0 = .Gson.Types.equals((Type) wildcardType0, (Type) class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int int0 = .Gson.Types.hashCodeOrZero((Object) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        .Gson.Types.typeToString((Type) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Class<Properties> class1 = Properties.class;
      Type type0 = .Gson.Types.resolve(class0, class1, class0);
      String string0 = .Gson.Types.typeToString(type0);
      assertEquals("java.lang.Object", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<String> class1 = String.class;
      Class class2 = (Class).Gson.Types.getGenericSupertype(class0, class1, class0);
      assertEquals(17, class2.getModifiers());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      Class<Object> class1 = Object.class;
      Class class2 = (Class).Gson.Types.getGenericSupertype(class1, class0, class1);
      assertNotNull(class2);
      assertEquals(1, class2.getModifiers());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Class<Object> class0 = Object.class;
      Type type0 = .Gson.Types.getArrayComponentType(class0);
      assertNull(type0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      Type type0 = .Gson.Types.getArrayComponentType(genericArrayType0);
      assertNull(type0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf(class0);
      Type type0 = .Gson.Types.resolve(class0, class0, genericArrayType0);
      assertNotNull(type0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      WildcardType wildcardType0 = .Gson.Types.supertypeOf(class0);
      Type type0 = .Gson.Types.resolve(wildcardType0, class0, wildcardType0);
      assertNotNull(type0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class0);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner((Type) null, class0, typeArray0);
      assertNotNull(parameterizedType0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      Type[] typeArray0 = .Gson.Types.getMapKeyAndValueTypes(class0, class0);
      ParameterizedType parameterizedType0 = .Gson.Types.newParameterizedTypeWithOwner(class0, class0, typeArray0);
      boolean boolean0 = .Gson.Types.equal(parameterizedType0, class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      GenericArrayType genericArrayType0 = .Gson.Types.arrayOf((Type) null);
      boolean boolean0 = .Gson.Types.equal(genericArrayType0, (Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      boolean boolean0 = .Gson.Types.equal(wildcardType0, class0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Class<Properties> class0 = Properties.class;
      Type[] typeArray0 = new Type[8];
      WildcardType wildcardType0 = .Gson.Types.subtypeOf(class0);
      typeArray0[7] = (Type) wildcardType0;
      Properties properties0 = new Properties();
      Object object0 = properties0.put(typeArray0[7], properties0);
      assertNull(object0);
  }
}
